let orderDeatils = {
  __v: 0,
  _id: "6744672626b698d00aebb621",
  acceptCaptain: {
    __v: 0,
    _id: "67444ca59bdda03116f20bdc",
    aadharCardDetails: null,
    address: "Hyderabad",
    adhar: null,
    adharBack: null,
    allVerificationStatus: false,
    captainLocation: { coordinates: [Array], type: "Point" },
    captainVehicleType: null,
    createdAt: "2024-11-25T10:08:37.108Z",
    dateOfBirth: "2000-12-23",
    email: "Chara@gmail.com",
    holdingCaptain: false,
    license: null,
    licenseCardDetails: null,
    licenseCardVerified: false,
    mobile: "9032180201",
    name: "Charan",
    onDuty: true,
    pan: null,
    panAadharCardVerified: false,
    panCardDetails: null,
    personalContact: null,
    profilePic: "uploads\\1732529317054.jpeg",
    rc: null,
    rcCardDetails: null,
    rcCardVerified: false,
    reviewToVerified: false,
    role: "captain",
    signUpCompletePercentage: 25,
    signUpDateAndTime: "2024-11-25T05:49:21.332Z",
    termsAndCondition: false,
    updatedAt: "2024-11-25T10:09:54.427Z",
    userVerified: false,
    vehicleNumber: null,
  },
  captainCoor: { lat: 17.4587337, lng: 78.3705527 },
  drop: { coordinates: [78.3475758, 17.4964692], type: "Point" },
  dropAddress: "Miyapur Police Station",
  dropVicinity: "Tiwari Nagar, Miyapur, Telangana, India",
  favorite: false,
  giveVehicleNumber: true,
  head: "674448b39bdda03116f20b1f",
  howManyMans: 0,
  isArrived: false,
  mensProblem: false,
  onNaviagtionChange: false,
  orderOtp: 3044,
  orderOtpVerified: false,
  orderPlaceDate: "25-11-2024",
  orderPlaceTime: "5:31:39 pm",
  pickup: { coordinates: [78.3705449, 17.4587069], type: "Point" },
  pickupAddress:
    "Sprint Business Centre, 6th Floor, Jayabheri Silicon Towers, Kothaguda, Hyderabad, Telangana 500084, India",
  price: 34,
  rejectedCaptaine: [],
  reviewTest: "",
  saved: false,
  status: "accept",
  userAuthenticationImage: null,
  vehicleType: "scooty",
};

let rideHistory = [
  {
    __v: 0,
    _id: "6745c625abfdce9d5a5c26a2",
    drop: { coordinates: [Array], type: "Point" },
    dropAddress: "Miyapur Police Station",
    dropVicinity: "Tiwari Nagar, Miyapur, Telangana, India",
    favorite: false,
    giveVehicleNumber: true,
    head: "674448b39bdda03116f20b1f",
    howManyMans: 0,
    isArrived: false,
    mensProblem: false,
    onNaviagtionChange: false,
    orderOtp: 5108,
    orderOtpVerified: false,
    orderPlaceDate: "26-11-2024",
    orderPlaceTime: "6:29:17 pm",
    pickup: { coordinates: [Array], type: "Point" },
    pickupAddress:
      "Sprint Business Centre, 6th Floor, Jayabheri Silicon Towers, Kothaguda, Hyderabad, Telangana 500084, India",
    price: 34,
    rejectedCaptaine: [],
    reviewTest: "",
    saved: false,
    status: "cancelled",
    userAuthenticationImage: null,
    vehicleType: "scooty",
  },
];

let profil = {
  __v: 0,
  _id: "6747788b11be4e1f4c9dd973",
  aadharCardDetails: null,
  address:
    "Rajiv Gandhi International Airport (HYD) | Shamshabad, Hyderabad, Telangana, India",
  adhar: "uploads\\1732737883192.jpeg",
  adharBack: "uploads\\1732737883195.jpeg",
  allVerificationStatus: false,
  captainLocation: { coordinates: [76.978987, 17.8765678], type: "Point" },
  captainVehicleType: null,
  createdAt: "2024-11-27T19:52:43.115Z",
  dateOfBirth: "2024-11-20",
  email: "chinni@gmail.com",
  fbtoken:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGUiOiI5NjY2NzU2ODcxIiwiaWF0IjoxNzMyNzc3OTkwfQ.SuEg0vPt3YlWZJEnHqzVNcUFk2K0IsqWsEbj8hFFKSg",
  holdingCaptain: false,
  license: null,
  licenseCardDetails: null,
  licenseCardVerified: false,
  mobile: "9666756871",
  mpin: "1245",
  name: "Chinni",
  onDuty: false,
  orders: [
    {
      _id: "674839d6327dfe1aee4f1d62",
      reviewRating: 4,
      reviewTest: "Goodhdy jfyfjgg hdygdtu",
    },
  ],
  pan: null,
  panAadharCardVerified: false,
  panCardDetails: null,
  personalContact: null,
  profilePic: null,
  rc: null,
  rcCardDetails: null,
  rcCardVerified: false,
  reviewToVerified: false,
  role: "user",
  scheduleOrderCount: 4,
  signUpCompletePercentage: 25,
  signUpDateAndTime: "2024-11-27T18:15:32.982Z",
  termsAndCondition: true,
  updatedAt: "2024-11-28T09:48:24.736Z",
  userVerified: false,
  vehicleNumber: null,
};

// vehicle Type scooty
//  LOG  price 1
//  LOG  placeName Sprint Business Centre, 6th Floor, Jayabheri Silicon Towers, Kothaguda, Hyderabad, Telangana 500084, India
//  LOG  dropAddress {"id": "ChIJ31MJbaOQyzsR3SvCCW2ETPA", "location": {"lat": 17.4578021, "lng": 78.36884549999999}, "name": "Kensium Solutions Pvt. Ltd.", "photo": "AdDdOWplh9ocDBdpmYurZNAHzZSeQi-F38t2BwazTsB1D7dHqYN2KLELg6QS-L-QblXeQRMBEVF-uboM3ygkEm6V8KU35M_wWpOjcKusnkLicq-RyeQfmmHPPtgoLCVdt3d8IhYDCSEY5w_fhLJtVsT8R2-YQIBEbv3oS8i6VlY8LJBfGewF", "vicinity": "4th Floor, Jyothi Pinnacle, Hitech City Road, Laxmi Cyber City, Whitefields, Kondapur"}
//  LOG  pickUpCoordinated {"lat": 17.4587261, "lng": 78.3705371}
//  LOG  orderId 674e9617c5fb38f26cac12f8

let or = {
  __v: 0,
  _id: "674e97288348dd92f7480355",
  attempts: 0,
  drop: { coordinates: [78.36884549999999, 17.4578021], type: "Point" },
  dropAddress: "Kensium Solutions Pvt. Ltd.",
  dropVicinity:
    "4th Floor, Jyothi Pinnacle, Hitech City Road, Laxmi Cyber City, Whitefields, Kondapur",
  favorite: false,
  futureTime: null,
  giveVehicleNumber: true,
  head: "6747788b11be4e1f4c9dd973",
  howManyMans: 0,
  isArrived: false,
  mensProblem: false,
  onNaviagtionChange: false,
  orderOtp: 1141,
  orderOtpVerified: false,
  orderPlaceDate: "3-12-2024",
  orderPlaceTime: "10:59:12 am",
  pickup: { coordinates: [78.3705371, 17.4587261], type: "Point" },
  pickupAddress:
    "Sprint Business Centre, 6th Floor, Jayabheri Silicon Towers, Kothaguda, Hyderabad, Telangana 500084, India",
  price: 1,
  rejectedCaptaine: [],
  reviewTest: "",
  saved: false,
  status: "cancelled",
  time: "",
  userAuthenticationImage: null,
  vehicleType: "scooty",
};

let previous = [
  {
    __v: 0,
    _id: "674ec31d4209bf509ee516cb",
    attempts: 0,
    drop: { coordinates: [Array], type: "Point" },
    dropAddress: "Swagath-De-Royal",
    dropVicinity:
      "Kothaguda Cross Road Cyberabad, Gachibowli - Miyapur Road, Kondapur",
    favorite: false,
    futureTime: null,
    giveVehicleNumber: true,
    head: "6747788b11be4e1f4c9dd973",
    howManyMans: 0,
    isArrived: false,
    mensProblem: false,
    onNaviagtionChange: false,
    orderOtp: 2021,
    orderOtpVerified: false,
    orderPlaceDate: "3-12-2024",
    orderPlaceTime: "2:06:45 pm",
    pickup: { coordinates: [Array], type: "Point" },
    pickupAddress:
      "4, Hitech City Rd, Kukatpally Housing Board Colony, Kukatpally, Hyderabad, Kothaguda, Telangana 500084, India",
    price: 4,
    rejectedCaptaine: [],
    reviewTest: "",
    saved: false,
    status: "pending",
    time: "",
    userAuthenticationImage: null,
    vehicleType: "scooty",
  },
];

let acceptOrder = {
  __v: 0,
  _id: "674fe4f35c1fd010fe2f299d",
  acceptCaptain: {
    __v: 0,
    _id: "6749921ad056e02f9d3e89a0",
    aadharCardDetails: null,
    address: "Fjdicnc",
    adhar: null,
    adharBack: null,
    allVerificationStatus: false,
    captainLocation: { coordinates: [Array], type: "Point" },
    captainVehicleType: null,
    createdAt: "2024-11-29T10:06:18.511Z",
    dateOfBirth: "2000-08-12",
    email: "vaddalanarasimha@gmail.com",
    emergencyContact: [[Object]],
    holdingCaptain: false,
    license: null,
    licenseCardDetails: null,
    licenseCardVerified: false,
    mobile: "8978106263",
    mpin: null,
    name: "Fhchf",
    onDuty: true,
    pan: null,
    panAadharCardVerified: false,
    panCardDetails: null,
    personalContact: null,
    profilePic: "uploads\\1732874778480.png",
    rc: null,
    rcCardDetails: null,
    rcCardVerified: false,
    reviewToVerified: false,
    role: "captain",
    scheduleOrderCount: 0,
    signUpCompletePercentage: 16,
    signUpDateAndTime: "2024-11-29T09:55:47.551Z",
    termsAndCondition: false,
    updatedAt: "2024-12-03T06:30:12.029Z",
    userVerified: false,
    vehicleNumber: null,
  },
  attempts: 0,
  drop: { coordinates: [78.4151554, 17.4816365], type: "Point" },
  dropAddress: "Kukatpally Police Station",
  dropVicinity:
    "BJP Office Road, Shanthi Nagar, Kukatpally, Hyderabad, Telangana, India",
  favorite: false,
  futureTime: null,
  giveVehicleNumber: true,
  head: "6747788b11be4e1f4c9dd973",
  howManyMans: 0,
  isArrived: false,
  mensProblem: false,
  onNaviagtionChange: false,
  orderOtp: 4942,
  orderOtpVerified: false,
  orderPlaceDate: "4-12-2024",
  orderPlaceTime: "10:43:23 am",
  pickup: { coordinates: [78.3705233, 17.4587463], type: "Point" },
  pickupAddress:
    "Sprint Business Centre, 6th Floor, Jayabheri Silicon Towers, Kothaguda, Hyderabad, Telangana 500084, India",
  price: 38,
  rejectedCaptaine: [],
  reviewTest: "",
  saved: false,
  status: "accept",
  time: "",
  userAuthenticationImage: null,
  vehicleType: "scooty",
};
