const data = {
  __v: 1,
  _id: "67b4296ae3d8b7db7f16f21a",
  aadharCarVerificaation: true,
  aadharCardDetails: null,
  accountDeleteRequestDate: null,
  accountDeleteStatus: "active",
  activeService: null,
  addedvehicleRcDetails: [],
  address: "Miyapur Hyderabad ",
  adhar: null,
  adharBack: null,
  adminDocsVerified: {
    adminAadharVerified: "initial",
    adminLicenVerified: "initial",
  },
  allVerificationStatus: false,
  averageRating: 4.81003786722819,
  captainLocation: { coordinates: [76.978987, 17.8765678], type: "Point" },
  captainVehicleType: null,
  createdAt: "2025-02-18T06:32:10.273Z",
  deletionReason: null,
  deviceId: "a7d3bea010996ffc",
  docsNumber: {
    dob: null,
    newAadharNumber: null,
    newLicenNumber: null,
    newPanNumber: null,
    newRcNumber: null,
  },
  donationActive: false,
  email: "johndoe@gmail.com",
  emergencyContact: [
    {
      _id: "67b5bf6f0b5e74e571aa237b",
      mobile: "+919177261975",
      name: "~Vanaja🙂🙂",
      option: "Night ride shared automatically (9PM - 6AM)",
    },
    {
      _id: "67b5bf790b5e74e571aa2384",
      mobile: "+91 93926 16319",
      name: "❤️Anu❤️❤️",
      option: "Night ride shared automatically (9PM - 6AM)",
    },
    {
      _id: "67b5bf7b0b5e74e571aa2391",
      mobile: "83748 89376",
      name: "💕💜Lover💜",
      option: "Night ride shared automatically (9PM - 6AM)",
    },
    {
      _id: "67b5bf7e0b5e74e571aa23a2",
      mobile: "93980 30842",
      name: "🥰🥰🥰Pappa🥰🥰",
      option: "Night ride shared automatically (9PM - 6AM)",
    },
  ],
  evenOnDuttyStopNotificationToRides: false,
  fbtoken:
    "dJj4pvmgRIGiGq6Kk9rX2Z:APA91bGYuVs0MbQq1-AHOEmLH_Sy07EqVQP_rwwu_BzPeUkiJz8n9uxEh3ziZkSjf4YmDF6ejGoIF-fPDgcyH8YjjBK8V-yb7HNYQu_DknqnkOXcBZ0dlbA",
  holdingCaptain: false,
  howManyMans: 0,
  languages: [],
  license: null,
  licenseBack: null,
  licenseCardDetails: null,
  licenseCardVerified: false,
  mobile: "8888888888",
  mpin: "2580",
  name: "John Doe ",
  onDuty: false,
  ownRefCode: "abc123",
  pan: null,
  panBack: null,
  panCardDetails: null,
  panCardVerified: false,
  profilePic: "uploads/1740155557971.jpg",
  rc: null,
  rcBack: null,
  rcCardDetails: null,
  rcCardVerified: false,
  rcNumber: null,
  referalCode: null,
  referralRewards: 0,
  reviewToVerified: false,
  role: "user",
  scheduleOrderCount: 0,
  services: [],
  signUpDateAndTime: "2025-02-17T03:19:40.769Z",
  termsAndCondition: false,
  updatedAt: "2025-02-21T18:12:45.690Z",
  userVerified: false,
  vehicleBackImage: null,
  vehicleFrontImage: null,
  vehicleHelmetImage: null,
  vehicleImageVerified: false,
  vehicleLeftImage: null,
  vehicleName: null,
  vehicleNumber: null,
  vehicleNumberPlate: null,
  vehicleRightImage: null,
  verificationInProgess: false,
  walletBalance: 0,
};
